sylius_twig_hooks:
    hooks:
        'app_shop.greeting.dynamic':
            content:
                template: '@GuiziwebSyliusTestPlugin/shop/greeting/dynamic/content.html.twig'
                priority: 0
        'app_shop.greeting.static':
            content:
                template: '@GuiziwebSyliusTestPlugin/shop/greeting/static/content.html.twig'
                priority: 0
